deps: update thiserror
error: use of irregular braces for `write!` macro
  --> format/src/error.rs:13:10
   |
13 | #[derive(Error)]
   |          ^^^^^
   |
   = note: `-D clippy::nonstandard-macro-braces` implied by `-D warnings`
help: consider writing `Error`
  --> format/src/error.rs:13:10
   |
13 | #[derive(Error)]
   |          ^^^^^
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#nonstandard_macro_braces
   = note: this error originates in the derive macro `Error` (in Nightly builds, run with -Z macro-backtrace for more info)

Unfortunately we can't update *everything* since rust-fuse uses time::Timespec,
which no longer exists in more modern versions of the package.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>